services:

  mysql_db:
    image: mysql:8.0.13
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3t
      MYSQL_DATABASE: db_file_upload
      MYSQL_USER: fileuploaduser
      MYSQL_PASSWORD: fileuploadpassword
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - backend
    restart: unless-stopped

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/db_file_upload?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: fileuploaduser
      SPRING_DATASOURCE_PASSWORD: fileuploadpassword
    depends_on:
      - mysql_db
    networks:
      - backend
    restart: always

volumes:
  mysql_data:
networks:
  backend:
    name: backend
    driver: bridge
